version: '3'

services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile.apache
    ports:
      - "8080:80"
    depends_on:
      - mysql

  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_mysql_user
      MYSQL_PASSWORD: your_mysql_password
