apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql
  template:
    metadata:
      labels:
        app: sql
    spec:
      containers:
      - name: sql-container
        image: karimachougri/sql_imagee
        ports:
        - containerPort: 3306
